### ISSUE TITLE
Établir le format du fichier YAML

### ISSUE THREAD

**Issue by cguertin14** [ClubCedille/pdf-autofiller#5]
* Définir les informations nécessaires à mettre dans le fichier YAML
* Établir une structure logique dans le fichier afin de bien organiser les informations
* Voir fichier PDF d'exemple pour établir les informations nécessaires

**Comment by AXDOOMER** [comment]
Spec v0.1:
```
# Une liste des champs attendus dans ce PDF
fields:
  apple:
    name: PDF field name in PDF document
    description: Explication descriptive du champs
  banane:
    name: Nom du champs du fichier PDF
    description: Explication descriptive du champs
  carotte:
    name: PDF field name
    description: explicit description
  dragon_fruit:
    name: DragonFruit
    description: Dragon Fruit

# Valeurs à insérer dans des champs
fill:
  apple:
    text: Ceci est une pomme
  banane: 
     # Étiré pour remplirt le champs, mais en respectant le rapport de cadre et centrée
     image: signature.jpg
  carotte: 
     image: signature.jpg
       x: 300
       y: 400
       width: 120
       height: 25
  dragon_fruit:
    text: ceci est un pitaya
```

Les clés qui se répètent peuvent être vues comme un désavantage (répétition, peut être inconsistent) ou comme un avantage si on aime la séparation. Les clés non-définies sous `fill` seraient demandées à l'utilisateur. La `description` sous `fields` aiderait à demander à l'utilisateur quelle information entrer, car la `description` est plus explicite que le nom du champs dans le PDF.

**Comment by cguertin14** [comment]
à quoi ça servirait d'avoir une liste de fields + une autre liste de fill? juste une des deux listes ne suffirait pas?

**Comment by AXDOOMER** [comment]
@cguertin14 Les deux pourraient être mergées (et ça serait peut-être une meilleure pratique?), mais en les ayant séparées, on peut distinguer les clés qui sont dedans servent à quoi. `fields` décrit les champs du PDF et ce qu'ils doivent contenir. `fill` contient des valeurs à insérer automatiquement dans le PDF. Les clefs de `fields` qui ne sont pas dans `fill` sont demandées à l'utilisateur.

**Comment by cguertin14** [comment]
Ok donc la section fields sert simplement à décrire chaque champ tandis que l'autre contient les actual values qu'on veut mettre dans le PDF dans le fond?

**Comment by AXDOOMER** [comment]
@cguertin14 Exact. La section `fields` devrait toujours être la même avec un document PDF correspondant. La section `fill` est celle qui devrait être personnalisée selon les besoins.

**Comment by cguertin14** [comment]
Ok c'est cool, c'est logique, peut-être que `fill` pourraient s'appeller `values` ou un nom plus explicit représentant un ensemble de valeur à utiliser par exemple

**Comment by AXDOOMER** [comment]
On devrait ajouter une clé au début de la config pour la faire correspondre au document correspondant:

```
file:
  name: Facture-xyz.pdf
  checksum: 25e97a74bcbf89e32817c2a863d9bc02097f2bb2f5169b564ff747ff874d2145
```
ou 
```
file:
  name: Facture-xyz.pdf
  checksum: 
    - 25e97a74bcbf89e32817c2a863d9bc02097f2bb2f5169b564ff747ff874d2145
    - e671843a54189839e23cbd10fa56ad2955bf0894eaf565a04d17a748b7d2c954
```

Ça serait un QOL improvement. L'idée c'est de que si on roule le programme avec seulement la config YML en CLI, il trouve le PDF correspondant à utiliser. Dans l'inverse, on spécifie la config YML et il trouve le fichier PDF correspondant. Comme ça, il y a un seul arg à spécifier au lieu de deux, à moins d’ambiguïtés. On pourrait faire correspondre les PDFs identiques mais qui n'ont pas le même filename par les checksums. 

C'est juste une idée car ça complexifie beaucoup notre affaire.

**Comment by AXDOOMER** [comment]
> Ok c'est cool, c'est logique, peut-être que `fill` pourraient s'appeller `values` ou un nom plus explicit représentant un ensemble de valeur à utiliser par exemple

`fill` est explicite car ça veut dire "remplissage" et c'est ce que cette section sert à faire.

**Comment by cguertin14** [comment]
ouais mais, avoir un verbe pour représenter une liste de valeurs fait plus ou moins de sens. Quelque chose comme `values` ou `filled-values` ou dequoi en français serait mieux

**Comment by AXDOOMER** [comment]
> ouais mais, avoir un verbe pour représenter une liste de valeurs fait plus ou moins de sens. Quelque chose comme `values` ou `filled-values` ou dequoi en français serait mieux

`filling` dans ce cas. "noun: a quantity of material that fills or is used to fill something."

J'hésite à utiliser des mots comme `keys` ou `values` parce que ce sont des mots utilisés pour définir certains éléments des languages de programmation, de markup ou de data definition.

**Comment by cguertin14** [comment]
`filling` c'est bien

**Comment by berbiche** [comment]
:-1: pour `filling`, je préfère `values` qui est beaucoup plus compréhensible et commun dans le langage que `filling`.

**Comment by GRV96** [comment]
Je comprends que vous voulez une racine (fields/filling/values) comme en XML, mais en YAML, ce n'est absolument pas nécessaire.

**Comment by GRV96** [comment]
J'ai répertorié les champs qui devraient être ignorés dans le fichier de définition des champs.

Inacessibles:
NoDoc (/Tx)
Verifié C/P (/Tx)
Date vérifié C/P (/Tx)
autorisation budgétaire (/Tx)
Date autorisation budgétaire (/Tx)

Servent de zones de texte:
libelSiEtudiant (/Tx)
Compte (/Btn)
CBS (/Btn)
UBR (/Btn)
DemFin (/Btn)
aaaa-mm-jj (/Btn)
aaaa-mm-jj-1 (/Btn)
aaaa-mm-jj-2 (/Btn)
aaaa-mm-jj-3 (/Btn)
aaaa-mm-jj-4 (/Btn)

Éléments graphiques:
barreH1 (/Tx)
barreH2 (/Tx)
barreV3 (/Tx)
barreV2 (/Tx)
barreV1 (/Tx)

Boutons de validation:
Valider-BAS (/Btn)
Valider-HAUT (/Btn)

Signatures
Je ne sais pas si on peut les insérer avec PyPDF2 ni si nous sommes censés le faire. Le demandeur ne doit mettre que la première.
SignatureDemandeur (/Tx)
SignatureRequérant (/Tx)
SignatureSupHiérarchique (/Tx)

**Comment by GRV96** [comment]
Je ne comprends pas l'utilité de la somme de contrôle [proposée par AXDOOMER](https://github.com/ClubCedille/pdf-autofiller/issues/5#issuecomment-770143796).

**Comment by berbiche** [comment]
Je crois qu'il faut remplir 2 signatures, la première est celle de l'étudiant et l'autre est celle du trésorier.

**Comment by AXDOOMER** [comment]
Le but c'est d'automatiser le remplissage des champs le plus possible. Le but du fichier YAML c'est de spécifier quoi mettre dans les champs à remplir pour ne pas avoir à les demander à l’utilisateur. Comme use case, on sait par exemple que le UBR de CEDILLE reste le même de facture en facture. La signature du trésorier reste toujours la même, etc.

Le fichier YAML permettrait aussi à l'outil de savoir comment demander à l'utilisateur de remplir un champs, parce que demander de remplir le champs `Compte (/Btn)` c'est pas clair. Le YAML doit donc fournir une description du champs, par exemple "numéro de compte". 

Pour ce qui est des sommes de contrôle, c'est pour pouvoir associer le fichier YAML avec un fichier automatiquement. Comme ça on n'a pas à spécifier à l'outil quel fichier YAML utiliser et quel PDF utiliser lorsqu'on veut remplir une facture.

**Comment by berbiche** [comment]
Si on définit les champs sous le format suivant (un schéma):

``` yaml
nom du champ 1:
  mapping: le nom du champs dans le formulaire
  optionnel: si le champ est optionnel? Je ne sais pas si nous avons besoin de ce type de champs
  type: int | str | bool ? Je ne sais pas si ce champ est pertinent
```

L'utilisateur utilise alors le YAML suivant:

``` yaml
nom du champ 1: valeur
```

Avec, par exemple, la ligne de commande suivante: `pdf-autofiller schema.yaml values.yaml`

À ce point, on réalise qu'on a un schéma YAML pour valider le YAML, hum <https://github.com/santhosh-tekuri/jsonschema>.
